"""empty message

Revision ID: 13698f4a2f63
Revises: d662c7dd56f0
Create Date: 2022-05-21 13:53:39.808982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13698f4a2f63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userss',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='userss_pkey'),
    sa.UniqueConstraint('email', name='userss_email_key'),
    sa.UniqueConstraint('name', name='userss_name_key')
    )
    # ### end Alembic commands ###
