"""empty message

Revision ID: 194f8a6dae95
Revises: 1e8bd14baf13
Create Date: 2022-06-10 13:11:58.826296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194f8a6dae95'
down_revision = '1e8bd14baf13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathon', sa.Column('slug', sa.String(length=4200), nullable=False))
    op.create_unique_constraint(None, 'hackathon', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hackathon', type_='unique')
    op.drop_column('hackathon', 'slug')
    # ### end Alembic commands ###
