"""empty message

Revision ID: 1e8bd14baf13
Revises: 033b8cf497ae
Create Date: 2022-06-10 12:07:36.891047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8bd14baf13'
down_revision = '033b8cf497ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathon', sa.Column('title', sa.String(length=42000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathon', 'title')
    # ### end Alembic commands ###
