"""empty message

Revision ID: 20bdeac4fc6e
Revises: 26c6d8aa0257
Create Date: 2022-05-29 12:12:13.940588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20bdeac4fc6e'
down_revision = '26c6d8aa0257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('admin')
    # op.drop_column('organisation', 'permission')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('permission', sa.VARCHAR(length=4200000), autoincrement=False, nullable=False))
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admin_pkey'),
    sa.UniqueConstraint('email', name='admin_email_key'),
    sa.UniqueConstraint('name', name='admin_name_key')
    )
    # ### end Alembic commands ###
