"""empty message

Revision ID: 2125ba85e1fe
Revises: 2908e446bda0
Create Date: 2022-05-21 11:30:35.109919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2125ba85e1fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userss', sa.Column('name', sa.String(length=128), nullable=False))
    op.create_unique_constraint(None, 'userss', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userss', type_='unique')
    op.drop_column('userss', 'name')
    # ### end Alembic commands ###
