"""test

Revision ID: 48d9e7b9b958
Revises: 
Create Date: 2022-05-21 10:33:22.361823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d9e7b9b958'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userss', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userss', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
