"""empty message

Revision ID: 59abbd3a52c9
Revises: bb666014138f
Create Date: 2022-05-22 12:22:39.940211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59abbd3a52c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('adminss')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminss',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='adminss_pkey'),
    sa.UniqueConstraint('email', name='adminss_email_key'),
    sa.UniqueConstraint('name', name='adminss_name_key'),
    )
    # ### end Alembic commands ###
