"""empty message

Revision ID: 75d8c003564a
Revises: 194f8a6dae95
Create Date: 2022-06-12 12:18:32.460686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d8c003564a'
down_revision = '194f8a6dae95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('userid', sa.Integer(), nullable=True))
    op.alter_column('token', 'tokenid',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'token', 'users', ['userid'], ['userid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.alter_column('token', 'tokenid',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('token', 'userid')
    # ### end Alembic commands ###
