"""empty message

Revision ID: 7d35b8638b4f
Revises: 20bdeac4fc6e
Create Date: 2022-05-29 12:56:24.870538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d35b8638b4f'
down_revision = '20bdeac4fc6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('users_organisation_fkey', 'users', type_='foreignkey')
    # op.drop_constraint('users_role_fkey', 'users', type_='foreignkey')
    # op.drop_column('users', 'organisation')
    # op.drop_column('users', 'role')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('organisation', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_role_fkey', 'users', 'roles', ['role'], ['roleid'])
    op.create_foreign_key('users_organisation_fkey', 'users', 'organisation', ['organisation'], ['orgaid'])
    # ### end Alembic commands ###
