version: '3.7'

networks:
  backend:
    name: flask-backend
  frontend:
    name: vue-frontend
  traefiknet:
    external: true

services:
  backend:
    build: ./backend
    container_name: flask
    restart: always
    environment: 
      - APP_NAME=FlaskApp
    networks:
      - backend
    volumes:
      - ./backend:/backend
    expose:
      - 5001
    # labels:
    #   - "traefik.enable=false"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    expose:
      - 8080
    networks:
      - traefiknet
      - backend
      - frontend
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:project.flask"
      - "traefik.backend=project.flask"
      - "traefik.enable=true"
      - "traefik.docker.network=traefiknet"

      
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    networks:
      - frontend
    expose:
      - 5000
    environment:
      - npm_config_unsafe_perm=true 
   
  
  app:
    container_name: reverse-proxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '83:80'
      - '81:81'
      # - '443:443'
    networks:
      - frontend
    volumes:
      - ./reverse-proxy/data:/data
      - ./reverse-proxy/letsencrypt:/etc/letsencrypt

