version: '3.7'

networks:
  backend:
    name: flask-backend
  frontend:
    name: vue-frontend

services:
  backend:
    build: ./backend
    container_name: flask
    restart: always
    environment: 
      - APP_NAME=FlaskApp
    networks:
      - backend
    volumes:
      - ./backend:/backend
    expose:
      - 5001

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    expose:
      - 8080
    networks:
      - backend
      - frontend
      
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    networks:
      - frontend
    expose:
      - 5000
    environment:
      - npm_config_unsafe_perm=true 
   
  
  app:
    container_name: reverse-proxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
    networks:
      - frontend
    volumes:
      - ./reverse-proxy/data:/data
      - ./reverse-proxy/letsencrypt:/etc/letsencrypt

