version: '3.7'

services:
  backend:
    command: > 
      sh -c "flask db stamp &&
      flask db upgrade &&
      uwsgi app.ini"    
    

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./frontend/dist:/var/www/html
      
  frontend:
    restart: on-failure    
    command: vue build
  
  