version: '3.7'

networks:
  backend:
    name: flask-backend
  frontend:
    name: vue-frontend

services:
  backend:
    build: ./backend
    container_name: flask
    environment: 
      - APP_NAME=FlaskApp
      - DATABASE_URL=postgresql://schoolhackathon:schoolhackathonpassword@database:5432/schoolhackathon
    networks:
      - backend
    volumes:
      - ./backend:/backend
    expose:
      - 5001
    depends_on:
      - "database"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always    
    expose:
      - 8080
    networks:
      - backend
      - frontend
    depends_on:
      - frontend
      - backend
      
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    networks:
      - frontend
    expose:
      - 5000
  
  app:
    container_name: reverse-proxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
    networks:
      - frontend
    volumes:
      - ./reverse-proxy/data:/data
      - ./reverse-proxy/letsencrypt:/etc/letsencrypt

  database:
    container_name: database
    image: postgres:14.3-alpine
    networks:
      - backend
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=schoolhackathon
      - POSTGRES_PASSWORD=schoolhackathonpassword
      - POSTGRES_DB=schoolhackathon
      